services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: 'http://myhostname.fake/docmost/'
      APP_SECRET: '123456789*/32132165465454632131321311'
      DATABASE_URL: 'postgresql://docmost:STRONG_DB_PASSWORD@db:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - docmost:/app/data/storage

  nginx-internal:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - docmost
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf:ro

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: STRONG_DB_PASSWORD
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  docmost:
  db_data:
  redis_data:
